### PR TITLE
Use shutdown hook to quit WebDriver once for all test classes

### PR DESCRIPTION
**Pull request by marcphilipp**
see discussion in junit-team/junit5-samples#29.

### CODE REVIEW

**Comment by paul-hammant** [comment]
Hey @marcphilipp thanks for the suggestion, but I'm never going to promote a solution that relies on a shutdown hook when I have a more instance-based alternative. I do like the inject-into-test-methods thing, so will implement that - thanks :)

**Comment by paul-hammant** [comment]
Interestingly, if I change the solution from constructor injection to arbitrary method injection, the `quit()` fails (NPE) because WebDriver isn't in the store. I think that's a bug.

**Comment by marcphilipp** [comment]
The NPE is thrown because you're accessing different `ExtensionContext.Store` objects.

The hierarchy looks like this:
```
(1) Engine Extension Context
 └─ (2) Class Extension Context
     └─ (3) Method Extension Context
```

You store it in the parent of (3) and later retrieve if from the parent of (2). Thus, the NPE. Please use the `getRoot()` method I wrote in both cases. That should solve the NPE.

**Comment by paul-hammant** [comment]
Parent of (3) is (2)?  There's a hierarchy there that I don't understand - Engine, Class (TestClass?), Method (TestMethod?). What is an engine in this case?  The JUnit5 appears to be an engine, but I would expect the implementation of the implicit runner (a container) to be hidden from the components (Tests, the Before/After doohickeys, etc). i.e. the principles of containment.

Either way, execution scopes have stores, and the stores are chained such that if there's a miss on one store, it silently traverses up the chain looking for the same key - right? Like so:

junit5_dag

**Comment by marcphilipp** [comment]
Yes, that's correct.

**Comment by marcphilipp** [comment]
Closing due to lack of activity. Feel free to take my changes and submit them should they still be relevant.

**Pull request closed without merging**
